// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1DMR7DUL79VSv7OWSZgxfpyWr15eos1A',
    appId: '1:909232006368:web:1452702494c4ab251d1c85',
    messagingSenderId: '909232006368',
    projectId: 'epharmacy-64f6f',
    authDomain: 'epharmacy-64f6f.firebaseapp.com',
    storageBucket: 'epharmacy-64f6f.appspot.com',
    measurementId: 'G-BP60DGHTYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm0alpsA6KtN9k6c6NzflXMk4lOQo4v18',
    appId: '1:909232006368:android:071b8e80e230e95b1d1c85',
    messagingSenderId: '909232006368',
    projectId: 'epharmacy-64f6f',
    storageBucket: 'epharmacy-64f6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEE__HLGAAQP5HS6HtvJKyZVqF2KnWXrU',
    appId: '1:909232006368:ios:3bea1cb8c1dae1111d1c85',
    messagingSenderId: '909232006368',
    projectId: 'epharmacy-64f6f',
    storageBucket: 'epharmacy-64f6f.appspot.com',
    iosClientId: '909232006368-56qjj76dias1qobbj140s0ptlvem7ni3.apps.googleusercontent.com',
    iosBundleId: 'com.example.ephamarcy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEE__HLGAAQP5HS6HtvJKyZVqF2KnWXrU',
    appId: '1:909232006368:ios:3bea1cb8c1dae1111d1c85',
    messagingSenderId: '909232006368',
    projectId: 'epharmacy-64f6f',
    storageBucket: 'epharmacy-64f6f.appspot.com',
    iosClientId: '909232006368-56qjj76dias1qobbj140s0ptlvem7ni3.apps.googleusercontent.com',
    iosBundleId: 'com.example.ephamarcy',
  );
}
